In [2]:
import pandas as pd

In [7]:
df = pd.read_csv('abs_2021census_i12_aust_sa2-7765933531659532694.csv')

In [11]:
for name in df.columns:
    print(name)

mhc_inc_dep_anx_age_45_54
 no_lthc_age_35_44
 no_lthc_age_tot
 stroke_age_25_34
 a_oth_lthc_age_45_54
 tot_per_age_0_14
 hd_inc_ha_ang_age_45_54
 not_st_age_35_44
 dem_inc_alz_age_35_44
 dia_exc_ges_dia_age_0_14
 dia_exc_ges_dia_age_15_24
 dia_exc_ges_dia_age_45_54
 arthritis_age_65_over
 a_oth_lthc_age_55_64
 dem_inc_alz_age_0_14
 arthritis_age_45_54
 a_oth_lthc_age_35_44
 kid_dis_age_55_64
 lc_inc_copd_emph_age_15_24
 mhc_inc_dep_anx_age_65_over
 not_st_age_25_34
 dia_exc_ges_dia_age_65_over
 asthma_age_45_54
 lc_inc_copd_emph_age_65_over
 hd_inc_ha_ang_age_0_14
 mhc_inc_dep_anx_age_55_64
 not_st_age_55_64
 kid_dis_age_15_24
 dia_exc_ges_dia_age_55_64
 kid_dis_age_35_44
 arthritis_age_tot
 lc_inc_copd_emph_age_45_54
 hd_inc_ha_ang_age_55_64
 hd_inc_ha_ang_age_15_24
 lc_inc_copd_emph_age_55_64
 tot_per_age_25_34
 tot_per_age_15_24
 asthma_age_tot
 cancer_inc_rem_age_45_54
 no_lthc_age_45_54
 hd_inc_ha_ang_age_35_44
 dem_inc_alz_age_15_24
 sa2_code_2021
 no_lthc_age_65_over
 kid_dis_age_0_14
 kid_dis_age_25_34
 cancer_inc_rem_age_25_34
 not_st_age_15_24
 arthritis_age_35_44
 stroke_age_35_44
 stroke_age_tot
 a_oth_lthc_age_15_24
 asthma_age_55_64
 mhc_inc_dep_anx_age_35_44
 kid_dis_age_tot
 tot_per_age_65_over
 stroke_age_0_14
 arthritis_age_15_24
 asthma_age_15_24
 arthritis_age_0_14
 tot_per_age_35_44
 stroke_age_65_over
 hd_inc_ha_ang_age_25_34
 hd_inc_ha_ang_age_tot
 a_oth_lthc_age_0_14
 dia_exc_ges_dia_age_35_44
 not_st_age_tot
 cancer_inc_rem_age_35_44
 not_st_age_0_14
 a_oth_lthc_age_25_34
 mhc_inc_dep_anx_age_0_14
 cancer_inc_rem_age_tot
 cancer_inc_rem_age_15_24
 dem_inc_alz_age_tot
 tot_per_age_tot
 dem_inc_alz_age_65_over
 stroke_age_15_24
 dem_inc_alz_age_45_54
 no_lthc_age_0_14
 dia_exc_ges_dia_age_25_34
 asthma_age_35_44
 lc_inc_copd_emph_age_35_44
 tot_per_age_45_54
 asthma_age_65_over
 cancer_inc_rem_age_55_64
 a_oth_lthc_age_tot
 lc_inc_copd_emph_age_25_34
 arthritis_age_25_34
 mhc_inc_dep_anx_age_tot
 no_lthc_age_15_24
 asthma_age_25_34
 not_st_age_65_over
 kid_dis_age_45_54
 dem_inc_alz_age_55_64
 asthma_age_0_14
 a_oth_lthc_age_65_over
 dem_inc_alz_age_25_34
 lc_inc_copd_emph_age_0_14
 tot_per_age_55_64
 stroke_age_45_54
 no_lthc_age_55_64
 mhc_inc_dep_anx_age_15_24
 stroke_age_55_64
 arthritis_age_55_64
 dia_exc_ges_dia_age_tot
 cancer_inc_rem_age_0_14
 not_st_age_45_54
 hd_inc_ha_ang_age_65_over
 cancer_inc_rem_age_65_over
 kid_dis_age_65_over
 no_lthc_age_25_34
 mhc_inc_dep_anx_age_25_34
 lc_inc_copd_emph_age_tot

In [16]:
df

,mhc_inc_dep_anx_age_45_54,no_lthc_age_35_44,no_lthc_age_tot,stroke_age_25_34,a_oth_lthc_age_45_54,tot_per_age_0_14,hd_inc_ha_ang_age_45_54,not_st_age_35_44,dem_inc_alz_age_35_44,dia_exc_ges_dia_age_0_14,...,arthritis_age_55_64,dia_exc_ges_dia_age_tot,cancer_inc_rem_age_0_14,not_st_age_45_54,hd_inc_ha_ang_age_65_over,cancer_inc_rem_age_65_over,kid_dis_age_65_over,no_lthc_age_25_34,mhc_inc_dep_anx_age_25_34,lc_inc_copd_emph_age_tot
0,3,8,55,0,3,35,0,0,0,0,...,6,3,0,3,0,0,0,6,5,5
1,24,26,325,0,14,215,5,7,0,0,...,18,39,0,3,9,4,3,43,23,17
2,3,3,96,0,0,51,0,0,0,0,...,0,7,0,0,0,0,0,28,4,0
3,12,21,275,0,9,157,4,3,0,0,...,9,22,0,4,3,0,0,22,12,9
4,0,4,55,0,0,30,0,0,0,0,...,3,3,0,0,0,0,0,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2448,0,0,9,0,0,8,0,0,0,0,...,0,0,0,0,0,0,0,3,0,0
2449,0,0,0,0,0,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2450,0,0,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2451,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2452,3,4,54,0,7,41,6,9,0,0,...,4,30,0,8,11,5,4,9,4,5

In [15]:
for i in range(df.shape[1]):
    non_null_count = df.iloc[i].notna().sum() # 统计某个feature有数值的量
    if (non_null_count < 10): # 数值比例少于10%
        print('not nan num in col ', i, ': ', non_null_count)

In [56]:
zeros_count = (df == 0).sum()
n = 0
deleted_lst = []
for index, value in zeros_count.items():
    if 'tot' not in index and 'sa2' not in index:
        deleted_lst.append(index)
        print(index)
        n+=1
n

mhc_inc_dep_anx_age_45_54
 no_lthc_age_35_44
 stroke_age_25_34
 a_oth_lthc_age_45_54
 hd_inc_ha_ang_age_45_54
 not_st_age_35_44
 dem_inc_alz_age_35_44
 dia_exc_ges_dia_age_0_14
 dia_exc_ges_dia_age_15_24
 dia_exc_ges_dia_age_45_54
 arthritis_age_65_over
 a_oth_lthc_age_55_64
 dem_inc_alz_age_0_14
 arthritis_age_45_54
 a_oth_lthc_age_35_44
 kid_dis_age_55_64
 lc_inc_copd_emph_age_15_24
 mhc_inc_dep_anx_age_65_over
 not_st_age_25_34
 dia_exc_ges_dia_age_65_over
 asthma_age_45_54
 lc_inc_copd_emph_age_65_over
 hd_inc_ha_ang_age_0_14
 mhc_inc_dep_anx_age_55_64
 not_st_age_55_64
 kid_dis_age_15_24
 dia_exc_ges_dia_age_55_64
 kid_dis_age_35_44
 lc_inc_copd_emph_age_45_54
 hd_inc_ha_ang_age_55_64
 hd_inc_ha_ang_age_15_24
 lc_inc_copd_emph_age_55_64
 cancer_inc_rem_age_45_54
 no_lthc_age_45_54
 hd_inc_ha_ang_age_35_44
 dem_inc_alz_age_15_24
 no_lthc_age_65_over
 kid_dis_age_0_14
 kid_dis_age_25_34
 cancer_inc_rem_age_25_34
 not_st_age_15_24
 arthritis_age_35_44
 stroke_age_35_44
 a_oth_lthc_age_15_24
 asthma_age_55_64
 mhc_inc_dep_anx_age_35_44
 stroke_age_0_14
 arthritis_age_15_24
 asthma_age_15_24
 arthritis_age_0_14
 stroke_age_65_over
 hd_inc_ha_ang_age_25_34
 a_oth_lthc_age_0_14
 dia_exc_ges_dia_age_35_44
 cancer_inc_rem_age_35_44
 not_st_age_0_14
 a_oth_lthc_age_25_34
 mhc_inc_dep_anx_age_0_14
 cancer_inc_rem_age_15_24
 dem_inc_alz_age_65_over
 stroke_age_15_24
 dem_inc_alz_age_45_54
 no_lthc_age_0_14
 dia_exc_ges_dia_age_25_34
 asthma_age_35_44
 lc_inc_copd_emph_age_35_44
 asthma_age_65_over
 cancer_inc_rem_age_55_64
 lc_inc_copd_emph_age_25_34
 arthritis_age_25_34
 no_lthc_age_15_24
 asthma_age_25_34
 not_st_age_65_over
 kid_dis_age_45_54
 dem_inc_alz_age_55_64
 asthma_age_0_14
 a_oth_lthc_age_65_over
 dem_inc_alz_age_25_34
 lc_inc_copd_emph_age_0_14
 stroke_age_45_54
 no_lthc_age_55_64
 mhc_inc_dep_anx_age_15_24
 stroke_age_55_64
 arthritis_age_55_64
 cancer_inc_rem_age_0_14
 not_st_age_45_54
 hd_inc_ha_ang_age_65_over
 cancer_inc_rem_age_65_over
 kid_dis_age_65_over
 no_lthc_age_25_34
 mhc_inc_dep_anx_age_25_34

91

In [57]:
age_lst = []
m = 0
for index, value in zeros_count.items():
    if 'per_age' in index and 'age_tot' not in index:
        age_lst.append(index)
        print(index)
        m+=1
m

 tot_per_age_0_14
 tot_per_age_25_34
 tot_per_age_15_24
 tot_per_age_65_over
 tot_per_age_35_44
 tot_per_age_45_54
 tot_per_age_55_64

7

In [58]:
df_deleted = df.drop(columns=deleted_lst)

In [59]:
df_deleted = df_deleted.drop(columns=age_lst)

In [60]:
df_deleted.shape

(2453, 15)

In [61]:
df_deleted.head()

,no_lthc_age_tot,arthritis_age_tot,asthma_age_tot,sa2_code_2021,stroke_age_tot,kid_dis_age_tot,hd_inc_ha_ang_age_tot,not_st_age_tot,cancer_inc_rem_age_tot,dem_inc_alz_age_tot,tot_per_age_tot,a_oth_lthc_age_tot,mhc_inc_dep_anx_age_tot,dia_exc_ges_dia_age_tot,lc_inc_copd_emph_age_tot
0,55,14,19,101021007,4,3,5,6,0,0,107,8,26,3,5
1,325,60,100,101021008,3,12,25,47,16,0,617,51,103,39,17
2,96,3,16,101021610,0,0,0,8,0,0,141,15,15,7,0
3,275,42,53,101021611,6,8,8,29,3,0,458,31,64,22,9
4,55,6,6,101031013,0,0,3,0,6,0,81,7,9,3,0

In [62]:
df_deleted.to_json('long_term_health.json', orient='index')

In [ ]:
df = pd.read_csv('abs_2021census_i12_aust_sa2-7765933531659532694.csv')